server:
  port: 8091
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

viacep:
  url: https://opencep.com/v1/%s
#  url: http://localhost:8085/%s